In [1]:
#Importing the basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.offline as py
from plotly import tools
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Reading the dataset
cars = pd.read_csv('car_acceptability.csv')
cars.shape

(1727, 7)

In [4]:
#sütun adları eklenmiştir
cars.columns = ['Buying', 'Maint', 'Doors','Persons','LugBoot','Safety','Class']

In [5]:
cars.sample(10)

Buying  Maint  Doors Persons LugBoot Safety  Class
1467    low   high      4       4   small    med    acc
1561    low    med      3    more     med   high  vgood
1059    med   high  5more       2     big    med  unacc
1353    low  vhigh      4       2     med    med  unacc
854    high    low  5more    more   small    low  unacc
100   vhigh  vhigh  5more    more   small   high  unacc
1577    low    med      4       4     med    low  unacc
716    high    med      4       4     big    low  unacc
975     med   high      2       2     med    med  unacc
161   vhigh   high      4       2   small    low  unacc

In [6]:
a_df=[]
for i in cars.values:
    if i[6] == 'acc':
        a_df.append(i)

In [7]:
df=pd.DataFrame(a_df)

In [8]:
df.sample(10)

0      1      2     3      4     5    6
147   high    low      2     4    big  high  acc
18   vhigh    med      4     4    med  high  acc
40   vhigh    low      2  more    med  high  acc
36   vhigh    low      2     4  small  high  acc
114   high    med      2  more    big  high  acc
178   high    low  5more  more    big   med  acc
215    med  vhigh  5more  more    big  high  acc
332    low   high      2     4  small  high  acc
318    low  vhigh      4  more    med  high  acc
21   vhigh    med      4  more  small  high  acc

In [9]:
#Veri setimizde eksik değer olup olmadığını kontrol edelim
cars.isnull().sum()

Buying     0
Maint      0
Doors      0
Persons    0
LugBoot    0
Safety     0
Class      0
dtype: int64

In [10]:
cars.describe()

Buying Maint Doors Persons LugBoot Safety  Class
count    1727  1727  1727    1727    1727   1727   1727
unique      4     4     4       3       3      3      4
top      high  high     3       4     med    med  unacc
freq      432   432   432     576     576    576   1209

In [11]:
cars.columns

Index(['Buying', 'Maint', 'Doors', 'Persons', 'LugBoot', 'Safety', 'Class'], dtype='object')

In [12]:
#Her bir değerlendirme kategorisindeki araba sayısını bulalım
cars['Class'].value_counts().sort_index()

acc       384
good       69
unacc    1209
vgood      65
Name: Class, dtype: int64

In [13]:
fig = {
  "data": [
    {
      "values": [1210,384,69,65],
      "labels": [
        "Unacceptable",
        "Acceptable",
        "Good",
        "Very Good"
      ],
      "domain": {"column": 0},
      "name": "Car Evaluation",
      "hoverinfo":"label+percent+name",
      "hole": .6,
      "type": "pie"
    }],
  "layout": {
        "title":"Distribution of Evaluated Cars",
        "grid": {"rows": 1, "columns": 1},
        "annotations": [
            {
                "font": {
                    "size": 36
                },
                "showarrow": False,
                "text": "",
                "x": 0.5,
                "y": 0.5
            }
        ]
    }
}
py.iplot(fig, filename='cars_donut')

In [14]:
#cars.Class.replace(('unacc', 'acc', 'good', 'vgood'), (0, 1, 2, 3), inplace = True)
#cars.Buying.replace(('vhigh', 'high', 'med', 'low'), (3, 2, 1, 0), inplace = True)
#cars.Maint.replace(('vhigh', 'high', 'med', 'low'), (3, 2, 1, 0), inplace = True)
#cars.Doors.replace(('5more'),(5),inplace=True)
#cars.Persons.replace(('more'),(5),inplace=True)
#cars.LugBoot.replace(('small','med','big'),(0,1,2),inplace=True)
#cars.Safety.replace(('low','med','high'),(0,1,2),inplace=True)

In [15]:
cars.Doors.replace(('5more'),('5'),inplace=True)
cars.Persons.replace(('more'),('5'),inplace=True)

In [16]:
features = cars.iloc[:,:-1]
features[:5]
a=[]
for i in features:
    a.append(features[i].value_counts())

In [17]:
buy = pd.crosstab(cars['Buying'], cars['Class'])
mc = pd.crosstab(cars['Maint'], cars['Class'])
drs = pd.crosstab(cars['Doors'], cars['Class'])
prsn = pd.crosstab(cars['Persons'], cars['Class'])
lb = pd.crosstab(cars['LugBoot'], cars['Class'])
sfty = pd.crosstab(cars['Safety'], cars['Class'])

In [18]:
buy

Class   acc  good  unacc  vgood
Buying                         
high    108     0    324      0
low      89    46    258     39
med     115    23    268     26
vhigh    72     0    359      0

In [24]:
data = [
    go.Bar(
        x=a[0].index,
        y=buy['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[0].index,
        y=buy['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[0].index,
        y=buy['good'],
        name='Good'
    ),
    go.Bar(
        x=a[0].index,
        y=buy['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Selling Price vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='distri')

In [25]:
data = [
    go.Bar(
        x=a[0].index,
        y=mc['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[0].index,
        y=mc['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[0].index,
        y=mc['good'],
        name='Good'
    ),
    go.Bar(
        x=a[0].index,
        y=mc['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Maintainance cost vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='cars_donut')

In [26]:
data = [
    go.Bar(
        x=a[2].index,
        y=drs['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[2].index,
        y=drs['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[2].index,
        y=drs['good'],
        name='Good'
    ),
    go.Bar(
        x=a[2].index,
        y=drs['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Doors vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='cars_donut')

In [27]:
data = [
    go.Bar(
        x=a[3].index,
        y=prsn['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[3].index,
        y=prsn['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[3].index,
        y=prsn['good'],
        name='Good'
    ),
    go.Bar(
        x=a[3].index,
        y=prsn['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Number of Passengers vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='cars_donut')

In [28]:
data = [
    go.Bar(
        x=a[4].index,
        y=lb['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[4].index,
        y=lb['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[4].index,
        y=lb['good'],
        name='Good'
    ),
    go.Bar(
        x=a[4].index,
        y=lb['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Luggage Boot vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='cars_donut')

In [30]:
data = [
    go.Bar(
        x=a[5].index,
        y=sfty['unacc'],
        name='Unacceptable'
    ),
    go.Bar(
        x=a[5].index,
        y=sfty['acc'],
        name='Acceptable'
    ),
    go.Bar(
        x=a[5].index,
        y=sfty['good'],
        name='Good'
    ),
    go.Bar(
        x=a[5].index,
        y=sfty['vgood'],
        name='Very Good'
    )

]

layout = go.Layout(
    barmode='stack',
    title='Safety vs Class'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='cars_donut')

In [31]:
#Veri çerçevesini x özelliklerine ve y hedef değişkenine bölme
x = cars.iloc[:, :-1]
y = cars.iloc[:, 6]

In [32]:
x.columns = ['Buying', 'Maint', 'Doors','Persons','LugBoot','Safety']
y.columns=['Class']

In [33]:
x.head()

Buying  Maint Doors Persons LugBoot Safety
0  vhigh  vhigh     2       2   small    med
1  vhigh  vhigh     2       2   small   high
2  vhigh  vhigh     2       2     med    low
3  vhigh  vhigh     2       2     med    med
4  vhigh  vhigh     2       2     med   high

In [34]:
x = pd.get_dummies(x, prefix_sep='_', drop_first=True)

In [35]:
x.sample(5)

Buying_low  Buying_med  Buying_vhigh  Maint_low  Maint_med  Maint_vhigh  \
397            0           0             1          1          0            0   
997            0           1             0          0          0            0   
1100           0           1             0          0          1            0   
1201           0           1             0          1          0            0   
454            0           0             0          0          0            1   

      Doors_3  Doors_4  Doors_5  Persons_4  Persons_5  LugBoot_med  \
397         0        1        0          0          1            0   
997         0        0        0          0          1            0   
1100        0        0        0          0          1            1   
1201        0        0        0          1          0            1   
454         0        0        0          0          1            1   

      LugBoot_small  Safety_low  Safety_med  
397               1           0           0  
997               0           0           0  
1100              0           1           0  
1201              0           0           0  
454               0           0           0

In [36]:
y.describe()

count      1727
unique        4
top       unacc
freq       1209
Name: Class, dtype: object

In [37]:
x=x.values
y=y.values

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [39]:
"""from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)"""

'from sklearn.preprocessing import StandardScaler\n\nsc = StandardScaler()\n\nx_train = sc.fit_transform(x_train)\nx_test = sc.transform(x_test)'

In [40]:
x_train[:5]

array([[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [41]:
y_train[:5]

array(['unacc', 'unacc', 'unacc', 'unacc', 'unacc'], dtype=object)

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [44]:
#Using Logistic regression
clf = LogisticRegression(random_state = 0)
clf.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [45]:
y_pred = clf.predict(x_test)
f1_LR=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.9081081081081082
Testing Accuracy:  0.8888888888888888
[[ 83   3  10   0]
 [  7   6   0   5]
 [ 16   0 282   0]
 [  7   0   0  13]]
              precision    recall  f1-score   support

         acc       0.73      0.86      0.79        96
        good       0.67      0.33      0.44        18
       unacc       0.97      0.95      0.96       298
       vgood       0.72      0.65      0.68        20

    accuracy                           0.89       432
   macro avg       0.77      0.70      0.72       432
weighted avg       0.89      0.89      0.89       432



In [46]:
#Using KNN classifier
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clf.fit(x_train, y_train)

KNeighborsClassifier()

In [47]:
y_pred = clf.predict(x_test)
f1_KNN=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.9266409266409267
Testing Accuracy:  0.8425925925925926
[[ 63   5  28   0]
 [  9   1   5   3]
 [  3   0 295   0]
 [  8   5   2   5]]
              precision    recall  f1-score   support

         acc       0.76      0.66      0.70        96
        good       0.09      0.06      0.07        18
       unacc       0.89      0.99      0.94       298
       vgood       0.62      0.25      0.36        20

    accuracy                           0.84       432
   macro avg       0.59      0.49      0.52       432
weighted avg       0.82      0.84      0.82       432



In [48]:
#Using Linear SVC
from sklearn.svm import SVC
clf = SVC(kernel = 'linear', random_state = 0)
clf.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [49]:
y_pred = clf.predict(x_test)
f1_SVC_Linear=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.9405405405405406
Testing Accuracy:  0.9282407407407407
[[ 86   4   6   0]
 [  1  11   0   6]
 [ 14   0 284   0]
 [  0   0   0  20]]
              precision    recall  f1-score   support

         acc       0.85      0.90      0.87        96
        good       0.73      0.61      0.67        18
       unacc       0.98      0.95      0.97       298
       vgood       0.77      1.00      0.87        20

    accuracy                           0.93       432
   macro avg       0.83      0.86      0.84       432
weighted avg       0.93      0.93      0.93       432



In [50]:
#Using rbf SVC
from sklearn.svm import SVC
clf = SVC(kernel = 'rbf', random_state = 0)
clf.fit(x_train, y_train)

SVC(random_state=0)

In [51]:
y_pred = clf.predict(x_test)
f1_SVC_rbf=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.976061776061776
Testing Accuracy:  0.9375
[[ 86   4   6   0]
 [  3  10   0   5]
 [  2   0 296   0]
 [  7   0   0  13]]
              precision    recall  f1-score   support

         acc       0.88      0.90      0.89        96
        good       0.71      0.56      0.63        18
       unacc       0.98      0.99      0.99       298
       vgood       0.72      0.65      0.68        20

    accuracy                           0.94       432
   macro avg       0.82      0.77      0.80       432
weighted avg       0.93      0.94      0.94       432



In [52]:
#Using NB classifier
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [53]:
y_pred = clf.predict(x_test)
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.48494208494208496
Testing Accuracy:  0.5
[[ 37  47   0  12]
 [  0  12   0   6]
 [ 96  36 147  19]
 [  0   0   0  20]]
              precision    recall  f1-score   support

         acc       0.28      0.39      0.32        96
        good       0.13      0.67      0.21        18
       unacc       1.00      0.49      0.66       298
       vgood       0.35      1.00      0.52        20

    accuracy                           0.50       432
   macro avg       0.44      0.64      0.43       432
weighted avg       0.77      0.50      0.56       432



In [54]:
#Trying decision tree classifier
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [55]:
y_pred = clf.predict(x_test)
f1_DT=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  1.0
Testing Accuracy:  0.8981481481481481
[[ 73   5  18   0]
 [  9   8   0   1]
 [  4   0 294   0]
 [  5   2   0  13]]
              precision    recall  f1-score   support

         acc       0.80      0.76      0.78        96
        good       0.53      0.44      0.48        18
       unacc       0.94      0.99      0.96       298
       vgood       0.93      0.65      0.76        20

    accuracy                           0.90       432
   macro avg       0.80      0.71      0.75       432
weighted avg       0.89      0.90      0.89       432



In [56]:
#Trying Random forest classifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 25, criterion = 'entropy', random_state = 0)
clf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=25, random_state=0)

In [57]:
y_pred = clf.predict(x_test)
f1_RF=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf.score(x_train, y_train))
print("Testing Accuracy: ", clf.score(x_test, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  1.0
Testing Accuracy:  0.875
[[ 71   6  19   0]
 [ 10   4   1   3]
 [  7   0 291   0]
 [  8   0   0  12]]
              precision    recall  f1-score   support

         acc       0.74      0.74      0.74        96
        good       0.40      0.22      0.29        18
       unacc       0.94      0.98      0.96       298
       vgood       0.80      0.60      0.69        20

    accuracy                           0.88       432
   macro avg       0.72      0.63      0.67       432
weighted avg       0.86      0.88      0.87       432



In [58]:
#Şimdi NB sınıflandırıcısını bu sefer yapay değişkenler olmadan yeniden deniyoruz
x_new = cars.iloc[:,:-1]

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
lae = LabelEncoder()
x_new=x_new.apply(lambda col: lae.fit_transform(col))
x_new.head()

Buying  Maint  Doors  Persons  LugBoot  Safety
0       3      3      0        0        2       2
1       3      3      0        0        2       0
2       3      3      0        0        1       1
3       3      3      0        0        1       2
4       3      3      0        0        1       0

In [61]:
x_new=x_new.values

In [62]:
x_train_new, x_test_new= train_test_split(x_new, test_size = 0.25, random_state = 0)

In [63]:
clf_new = GaussianNB(priors=None)
clf_new.fit(x_train_new, y_train)

GaussianNB()

In [64]:
y_train[:10]

array(['unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc',
       'unacc', 'unacc'], dtype=object)

In [65]:
y_pred = clf_new.predict(x_test_new)
f1_NB=f1_score(y_test,y_pred, average='macro')
print("Training Accuracy: ",clf_new.score(x_train_new, y_train))
print("Testing Accuracy: ", clf_new.score(x_test_new, y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

Training Accuracy:  0.6447876447876448
Testing Accuracy:  0.625
[[  9   0  40  47]
 [  2   0   4  12]
 [  6   0 241  51]
 [  0   0   0  20]]
              precision    recall  f1-score   support

         acc       0.53      0.09      0.16        96
        good       0.00      0.00      0.00        18
       unacc       0.85      0.81      0.83       298
       vgood       0.15      1.00      0.27        20

    accuracy                           0.62       432
   macro avg       0.38      0.48      0.31       432
weighted avg       0.71      0.62      0.62       432



In [66]:
models=['Linear SVC', 'Kernel SVC','Logistic Regression','Decision Tree Classifier','Random Forest Classifier','Naive Bayes Classifier' ]
fig = go.Figure(data=[
    go.Bar(name='f1_score', x=models, y=[f1_SVC_Linear,f1_SVC_rbf,f1_LR,f1_DT,f1_RF,f1_NB])])
fig.show()